version: '3'

services:
    datacapsule-crossref-jupyter:
        build:
            context: .
            dockerfile: Dockerfile.jupyter
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        command: start-notebook.sh --NotebookApp.token=''
        ports:
            - "${DATACAPSULE_CROSSREF_JUPYTER_PORT}:8888"
        volumes:
            - .:/home/jovyan/datacapsule-crossref-jupyter
