version: '3'

services:
  datacapsule-crossref:
    volumes:
      - ./data:/data
      - ~/.config/figshare:/$USER/.config/figshare
    environment:
      - USER=$USER
      - HOME=/$USER

  jupyter:
    volumes:
      - .:/home/jovyan/datacapsule-crossref-jupyter
